# Site settings
title: Andy Zhang's Blog
description: > # this means to ignore newlines until "baseurl:"
  Irregularly updated and typically outdated.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://zhangbanger.github.io" # the base hostname & protocol for your site
github_username:  zhangbanger
twitter_username: zhangandyx

# Build settings
markdown: kramdown

kramdown:
  input: GFM
